services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: thinkon
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webnet

  web1:
    container_name: web1
    build: ./web
    networks:
      - webnet
    depends_on:
      - db


  web2:
    container_name: web2
    build: ./web
    networks:
      - webnet
    depends_on:
      - db

  web3:
    container_name: web3
    build: ./web
    networks:
      - webnet
    depends_on:
      - db

  haproxy:
    image: haproxy:2.9
    depends_on:
      - web1
      - web2
      - web3
    ports:
      - "8080:80"      # public web access
      - "8404:8404"    # HAProxy stats page (optional)
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - webnet

networks:
  webnet:
